Simplify semantics
jenkinsci/maven-hpi-plugin pull request #375
Opened 2022-08-09 21:29 UTC by basil

If I am understanding #373 then there is no real use case where one would ever want to set `overrideWar` but not also `jth.jenkins-war.path`, so let's just consume the `jth.jenkins-war.path` property directly the same way the test harness does instead of forcing the user to specify to options both pointing to the same file. With that semantic in place, there is no need to add dependencies not already present in the project model to the project model, since the use case of testing plugin-to-plugin interaction is handled by setting `jth.jenkins-war.path`, and such a use case probably doesn't exist for someone who is setting `overrideVersions` but not `jth.jenkins-war.path`.

2022-08-09 21:53 UTC, basil reviewed
The only downside to these semantics would be if there are any consumers that would not want to get this behavior when passing `jth.jenkins-war.path` (unlikely I think) or if they would not want to pass `jenkins.version` which is required when overriding from a WAR in `maven-hpi-plugin` (maybe slightly more likely but probably OK?)

2022-08-10 13:15 UTC, jglick commented
> there is no real use case where one would ever want to set `overrideWar` but not also `jth.jenkins-war.path`

There is a use case, and CloudBees has it: we wish to pick up plugin versions from a WAR (hence `overrideWar`) but setting `jth.jenkins-war.path` causes all sorts of complicated failures.

2022-08-10 13:17 UTC, jglick requested changes
This change would prevent CloudBees from adopting the new PCT mode.

2022-08-10 14:34 UTC, basil commented
Would have been nice to simplify the API, but cannot do so while still supporting all existing consumers.

2022-08-10 14:34 UTC, closed without merging